version: '3.8'
services:
  front:
    build:
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - .:/app  # Assurez-vous que le chemin correspond Ã  celui dans le Dockerfile
    ports:
      - 3000:3000
